CREATE TABLE IF NOT EXISTS users (
    id  bigint generated by default as identity primary key,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION get_user_name(user_id INT) 
RETURNS VARCHAR AS $$
DECLARE
    result VARCHAR;
BEGIN
    SELECT name INTO result FROM users WHERE id = user_id;
    RETURN result;
END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION create_user(user_name TEXT, user_description TEXT)
RETURNS INT AS $$
DECLARE
    new_user_id INT;
BEGIN
    INSERT INTO users (name, description)
    VALUES (user_name, user_description)
    RETURNING id INTO new_user_id;
    
    RETURN new_user_id;
END;
$$ LANGUAGE plpgsql;